export const initialCreateJobCircularInputState = {
  slug: '',
  jobPosition: '',
  totalNumberVacancy: '',
  jobContext: '',
  jobResponsibility: '',
  employmentStatus: '',
  educationalRequirement: '',
  experienceRequirements: '',
  additionalRequirements: '',
  religion: '',
  age: '',
  gender: '',
  jobLocation: '',
  salary: '',
  compensationAndOtherBenefits: '',
  applicationDeadline: '',
  publishedDate: '',
  applicationInstruction: '',
  publishStatus: '',
};
