### Login Request
# @name login

POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

## Request Body
{
    "email": "super.admin@email.com",
    "password": "password"
}

### Set Token
@token = {{login.response.body.data.access_token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# @name getUsers
GET http://127.0.0.1:8000/api/users?page=1&per_page=2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
